[tools]
"aqua:biome" = "latest"
"aqua:dprint" = "latest"
"aqua:evilmartians/lefthook" = "latest"
"aqua:go-task/task" = "latest"
"aqua:nodejs/node" = "22"
"aqua:pnpm" = "10"
"npm:@antfu/ni" = "latest"
