# https://taskfile.dev
version: "3"

tasks:
  default:
    aliases:
      - list
    cmd: task --list-all

  fix:
    cmds:
      - biome check --write
      - dprint fmt

  check:
    deps:
      - check:biome
      - check:dprint
      - check:tsc

  check:biome:
    cmds:
      - biome check

  check:dprint:
    cmds:
      - dprint check

  check:tsc:
    cmds:
      - pnpm tsc --noEmit
      - deno check .
