# https://taskfile.dev
version: "3"

tasks:
  default:
    aliases:
      - list
    cmd: task --list-all

  setup:
    cmds:
      - cmd: lefthook uninstall
        silent: true
        ignore_error: true
      - cmd: lefthook install

  fix:
    cmds:
      - na biome check --write
      - na dprint fmt

  check:
    deps:
      - check:biome
      - check:dprint
      - check:tsc

  check:biome:
    cmds:
      - na biome check

  check:dprint:
    cmds:
      - na dprint check

  check:tsc:
    cmds:
      - na tsc
      # - deno check .
