# https://taskfile.dev
version: "3"

tasks:
  default:
    aliases:
      - list
    cmd: task --list-all

  fix:
    cmds:
      - biome check --write
      - dprint fmt

  check:
    deps:
      - check:biome
      - check:dprint
      - check:tsc

  check:biome:
    cmds:
      - biome check

  check:dprint:
    cmds:
      - dprint check

  check:tsc:
    cmds:
      - deno check .

  build:
    cmds:
      - deno publish --dry-run --allow-dirty

  run:
    cmds:
      - deno run -A cli/cli.ts --branch=main --limit=10 totto2727-org function effect effect
