# https://taskfile.dev
version: '3'

tasks:
  default:
    aliases:
      - list
    cmd: task --list-all

  fix:
    cmds:
      - biome check --write
      - dprint fmt --allow-no-files

  build:
    cmds:
      - deno publish --dry-run --allow-dirty
